# Grafana SSO. The grafana release itself is managed by the core stack; this
# only creates the authentik OIDC client and the credential secret it reads.
module "grafana_oidc" {
  source    = "../../modules/monitoring/grafana_oidc"
  namespace = "monitoring"
  domain    = var.deployment.common.domain
}

# Human ntfy users.
#
# These are created against the RUNNING server (kubectl exec + ntfy's own CLI),
# not through config-file provisioning: ntfy's config keys (auth-users /
# auth-access / auth-tokens) are each ONE comma-joined value with exactly one
# author, and core owns them for the service accounts. Users created this way
# are ordinary database rows (provisioned = 0), so core's config can never
# clobber or delete them.
#
# The list comes from tfvars (both stacks read the same file):
#
#   ntfy = {
#     users = {
#       jblack = {
#         role   = "user"
#         access = [{ topic = "alerts", permission = "read-write" }]
#       }
#     }
#   }
#
# Passwords are generated by the module and stored in the `ntfy-users` Secret.
# Apply this stack AFTER core (the exec needs the ntfy pod).
module "ntfy_users" {
  source    = "../../modules/monitoring/ntfy_users"
  namespace = "monitoring"
  users     = try(var.deployment.ntfy.users, {})
}
